-- 시퀀스(SEQUENCE) : 자동 번호 발생기
CREATE SEQUENCE SEQ_EMPID -- 시퀀스 이름 지정
START WITH 300 -- 시작 숫자
INCREMENT BY 5 -- 증가 숫자
MAXVALUE 310 -- 최대 숫자
NOCYCLE -- 사이클 안 돌겠다 ( NOCYCLE이 기본값 )
NOCACHE; -- 메모리 상에서 관리하지 않겠다

SELECT * FROM USER_SEQUENCES;

-- SEQUENCE 사용
-- 시퀀스명.CURRVAL : 현재 생성된 시퀀스의 값
-- 시퀀스명.NEXTVAL : 시퀀스를 증가시키거나 최초로 시퀀스를 실행
--                   --------- => 시퀀스명.NEXTVAL = 시퀀스명.CURRVAL + INCREMENT로 지정한 값
SELECT SEQ_EMPID.CURRVAL FROM DUAL;
-- sequence SEQ_EMPID.CURRVAL is not yet defined in this session
-- 최초로 실행 시 NEXTVAL을 해줘야 하는데 CURRVAL을 먼저 사용했기 때문에 에러 발생 

SELECT SEQ_EMPID.NEXTVAL FROM DUAL; -- 300
SELECT SEQ_EMPID.CURRVAL FROM DUAL; -- 300
SELECT SEQ_EMPID.NEXTVAL FROM DUAL; -- 305
SELECT SEQ_EMPID.NEXTVAL FROM DUAL; -- 310
SELECT SEQ_EMPID.NEXTVAL FROM DUAL; 
-- sequence SEQ_EMPID.NEXTVAL exceeds MAXVALUE and cannot be instantiated
-- MAXVALUE를 310으로 지정해줬기 때문에 이를 넘어섰기 때문에 에러 발생

SELECT SEQ_EMPID.CURRVAL FROM DUAL; -- 310
-- LAST NUMBER를 따라가는 것이 아니라 성공적으로 호출된 마지막 NEXTVAL의 값을 갖고 있음 

-- CURRVAL / NEXTVAL 사용 가능 및 불가능
-- 사용 가능
--      서브쿼리가 아닌 SELECT문
--      INSERT문의 SELECT절
--      INSERT문의 VALUES절
--      UPDATE문의 SET절
-- 사용 불가능
--      VIEW의 SELECT절
--      DISTINCT키워드가 있는 SELECT문
--      GROUP BY, HAVING, ORDER BY 절의 SELECT문
--      SELECT, UPDATE, DELETE문의 서브쿼리
--      CREATE TABLE, ALTER TABLE의 DEFAULT값

-- 시작 숫자가 300이고 증가 값은 1이며 최대 숫자가 10000인 비순환 및 캐시 사용을 안하는 SEQ_EID 시퀀스 생성
CREATE SEQUENCE SEQ_EID
START WITH 300
-- INCREMENT BY 1
MAXVALUE 10000
NOCYCLE
NOCACHE;

COMMIT;

INSERT INTO EMPLOYEE 
VALUES(SEQ_EID.NEXTVAL, '홍길동', '666666-6666666', 'hong_gd@hk.or.kr', '01066666666', 'D2', 'J7', 's1',
        5000000, 0.1, 200, SYSDATE, NULL, DEFAULT);

SELECT * FROM EMPLOYEE;

-- SAL_LEVEL 값 변경 연습
-- UPDATE EMPLOYEE
-- SET SAL_LEVEL = 'S1'
-- WHERE EMP_ID = 300;

CREATE TABLE TMP_EMPLOYEE(
    E_ID NUMBER DEFAULT SEQ_EID.NEXTVAL,
    E_NAME VARCHAR2(30)
);
-- column not allowed here
-- DEFAULT문에서 SEQUENCE 사용 불가능하다고 에러 발생

ROLLBACK;

-- 시퀀스 변경
ALTER SEQUENCE SEQ_EMPID
INCREMENT BY 10
MAXVALUE 400
NOCYCLE
NOCACHE;

SELECT * FROM USER_SEQUENCES;
-- START WITH 값은 변경 불가

SELECT SEQ_EMPID.NEXTVAL FROM DUAL; -- 320
SELECT SEQ_EMPID.CURRVAL FROM DUAL; -- 320
